name: EMCRecipies
version: ${project.version}
description: ${project.description}
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
main: com.karlofduty.EMCRecipies.EMCRecipies
api-version: 1.13